[profile.default]
src = "contracts"
test = "test"
script = "scripts"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
tempo = true
eth_rpc_url = "moderato"

[rpc_endpoints]
moderato = "${TEMPO_TESTNET_RPC_URL}"

[profile.default.model_checker]
contracts = {}
